steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'weather-mcp-server'
      - '--image=gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--set-env-vars=NWS_USER_AGENT=weather-mcp-server@example.com'
      - '--set-env-vars=LOG_LEVEL=INFO'
      - '--set-env-vars=WEATHER_API_HOST=api.weather.gov'
      - '--set-env-vars=WEATHER_API_PORT=443'
      - '--set-env-vars=WEATHER_API_PROTOCOL=https'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'
